### ISSUE TITLE
CoderDojo 西宮・梅田は別々に dojos.yaml に追加する?

### ISSUE THREAD

**Issue by yasulab** [coderdojo-japan/coderdojo.jp#233]
CoderDojo 奈良・生駒のようにそれぞれ別々に dojos.yaml に追加して、同じウェブサイトを参照するような形にすると良さそう? 🤔

## CoderDojo 奈良・生駒の例

<img width="492" alt="coderdojo nara ikoma" src="https://user-images.githubusercontent.com/155807/34656237-0a0e7206-f45a-11e7-883e-09d9f3a5522e.png">
ロゴは別々だけど、参照先のURLは同じ: http://coderdojo-nara-ikoma.github.io/

```
- id: 35
  created_at: '2014-10-26'
  order: '292010'
  name: 奈良 (近畿)
  prefecture_id: 29
  url: http://coderdojo-nara-ikoma.github.io/
  logo: https://raw.githubusercontent.com/coderdojo-nara-ikoma/document/master/icon/NARA_black.png
  description: 奈良県奈良市で毎月開催
  tags:
  - Scratch
  - Webサイト
  - C#
- id: 36
  created_at: '2016-04-25'
  order: '292095'
  name: 生駒 (近畿)
  prefecture_id: 29
  logo: https://raw.githubusercontent.com/coderdojo-nara-ikoma/document/master/icon/IKOMA_green.png
  url: http://coderdojo-nara-ikoma.github.io/
  description: 奈良県生駒市で毎月開催
  tags:
  - Scratch
  - Webサイト
  - C#
```
