### ISSUE TITLE
CoderDojo 岡南 の Dojo情報の変更

### ISSUE THREAD

**Issue by yu-san-19** [coderdojo-japan/coderdojo.jp#678]
お世話になります。岡南道場の以下のように情報の変更をお願いします。

- db/dojos.yml
```yaml diff
# db/dojos.yml
- id: 81
  order: '331007'
  created_at: '2017-03-20'
  name: 岡南 # <- 岡山 岡南 
  prefecture_id: 33
  logo: "/img/dojos/okayama.png"
  url: https://www.coderdojo-konan.jp/
  description: 岡山市南区で毎月第3日曜に開催 # <- 岡山県岡山市南区で毎月開催
  tags:
  - Scratch
  - Unity
  - Python
  - C#
  - Webアプリ開発
```

- ロゴの差し替え - [新ロゴ元ファイル](https://drive.google.com/file/d/18BL5xKwEbtpiVzoBt-yraU7wBwEJXwOI/view?usp=sharing)
- イベントの集計元を connpass から doorkeeper へ変更
  - group: `coderdojo-konan`
  - group id: `9993 `

お手数をおかけするのも申し訳ないので、僕がきちんと自分で変更して PR を開く感じにしたかったのですが、clone したものの docker と docker じゃない方の両方で `Scrivito::ClientError: Please provide valid credentials via HTTP Authentication` というエラーでうまく動かなかったので... すみません...
（エラーの方は別で issue 開いた方が良かったでしょうか...?

よろしくお願いします 🙇
